services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    container_name: tic-tac-toe-backend

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    container_name: tic-tac-toe-frontend
    depends_on:
      - backend
